{% set version = "1.2.4" %}
{% set gh_org = "scikit-learn-contrib" %}
{% set gh_repo = "categorical_encoding" %}
{% set pkg_name = "category_encoders" %}


package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: {{ pkg_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: b3342686fcb9718e6475b48a725477da06cf9bce0345e9484b4cad9cd1ff5e2e

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - numpy >=1.9.0
    - pandas >=0.16.0
    - patsy >=0.4.0
    - python
    - scikit-learn >=0.15.0
    - scipy >=0.9
    - statsmodels >=0.6.0

test:
  requires:
    - nose
    - python
  imports:
    - category_encoders
  commands:
    - nosetests {{ pkg_name }}

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  license_family: BSD
  summary: A collection of sklearn transformers to encode categorical variables as numeric

extra:
  recipe-maintainers:
    - bollwyvl
    - wdm0006
